Nhom1_LTWEB_Webbandongho/Areas/Admin/Controllers/CatelogyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nhom1_LTWEB_Webbandongho.Areas.Admin.Models;
using Nhom1_LTWEB_Webbandongho.Models;
using Nhom1_LTWEB_Webbandongho.Repositories;

namespace Nhom1_LTWEB_Webbandongho.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CatelogyController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        public CatelogyController(IProductRepository productRepository,
        ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }
        public async Task<IActionResult> Index()
        {
            var catelogys = await _categoryRepository.GetAllAsync();
            return View(catelogys);
        }
        public async Task<IActionResult> Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(Category category)
        {
            await _categoryRepository.AddAsync(category);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int id)
        {
            var catelogy = await _categoryRepository.GetByIdAsync(id);
            if (catelogy == null)
            {
                return NotFound();
            }
           
            return View(catelogy);
        }
        // Xử lý cập nhật sản phẩm
        [HttpPost]
        public async Task<IActionResult> Update(int id,Category category)
        {
           
            if (ModelState.IsValid)
            {
                var existingCatelogy = await _categoryRepository.GetByIdAsync(id);
               
                // Cập nhật các thông tin khác của sản phẩm
                existingCatelogy.Name = category.Name;
                
                await _categoryRepository.UpdateAsync(existingCatelogy);
                return RedirectToAction(nameof(Index));
            }
           
            return View(category);
        }
    }
}

Nhom1_LTWEB_Webbandongho/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nhom1_LTWEB_Webbandongho.Areas.Admin.Models;
using Nhom1_LTWEB_Webbandongho.Models;
using Nhom1_LTWEB_Webbandongho.Repositories;
using X.PagedList;
namespace Nhom1_LTWEB_Webbandongho.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        public ProductController(IProductRepository productRepository,
        ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }
        // Hiển thị danh sách sản phẩm
        public async Task<IActionResult> Index(int? page,String searchString)
        {
            if (page == null)
            {
                page = 1;
            }
            var pageNumber = page ?? 1; // Số trang mặc định là trang 1
            var pageSize = 5; // Số lượng mục trên mỗi trang
            var products = await _productRepository.GetAllAsync();
            if (!string.IsNullOrEmpty(searchString))
            {
                products = await _productRepository.GetByNameAsync(searchString);
            }

            return View(products.ToPagedList(pageNumber, pageSize));
        }

        public async Task<IActionResult> Add()
        {
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View();
        }
        // Xử lý thêm sản phẩm mới
        [HttpPost]
        public async Task<IActionResult> Add(Product product, IFormFile imageUrl)
        {
            if (ModelState.IsValid)
            {
                if (imageUrl != null)
                {
                    // Lưu hình ảnh đại diện tham khảo bài 02 hàm SaveImage
                    product.ImageUrl = await SaveImage(imageUrl);
                }
                await _productRepository.AddAsync(product);
                return RedirectToAction(nameof(Index));
            }
            // Nếu ModelState không hợp lệ, hiển thị form với dữ liệu đã nhập
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View(product);
        }
        // Viết thêm hàm SaveImage (tham khảo bài 02)
        private async Task<string> SaveImage(IFormFile image)
        {
            var savePath = Path.Combine("wwwroot/images", image.FileName);

            using (var fileStream = new FileStream(savePath, FileMode.Create))
            {
                await image.CopyToAsync(fileStream);
            }
            return "/images/" + image.FileName; // Trả về đường dẫn tương đối
        }

        public async Task<IActionResult> Display(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        // Hiển thị form cập nhật sản phẩm
        public async Task<IActionResult> Update(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name",product.CategoryId);
            return View(product);
        }
        // Xử lý cập nhật sản phẩm
        [HttpPost]
        public async Task<IActionResult> Update(int id, Product product, IFormFile imageUrl)
        {
            ModelState.Remove("ImageUrl"); // Loại bỏ xác thực ModelState choImageUrl
            if (id != product.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var existingProduct = await
                _productRepository.GetByIdAsync(id);
                if (imageUrl == null)
                {
                    product.ImageUrl = existingProduct.ImageUrl;
                }
                else
                {
                    // Lưu hình ảnh mới
                    product.ImageUrl = await SaveImage(imageUrl);
                }
                // Cập nhật các thông tin khác của sản phẩm
                existingProduct.Name = product.Name;
                existingProduct.Price = product.Price;
                existingProduct.Description = product.Description;
                existingProduct.CategoryId = product.CategoryId;
                existingProduct.ImageUrl = product.ImageUrl;
                await _productRepository.UpdateAsync(existingProduct);
                return RedirectToAction(nameof(Index));
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View(product);
        }
        // Hiển thị form xác nhận xóa sản phẩm
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        // Xử lý xóa sản phẩm
        [HttpPost, ActionName("DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Nhom1_LTWEB_Webbandongho/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Options;
using Microsoft.EntityFrameworkCore;
using Nhom1_LTWEB_Webbandongho.Areas.Admin.Models;
using Nhom1_LTWEB_Webbandongho.Models;
using Nhom1_LTWEB_Webbandongho.Repositories;
using X.PagedList;

namespace Nhom1_LTWEB_Webbandongho.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly IUserRespository _userRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        public UserController(IUserRespository userRepository, RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _userRepository = userRepository;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int? page, String searchString)
        {
            if (page == null)
            {
                page = 1;
            }
            var pageNumber = page ?? 1; // Số trang mặc định là trang 1
            var pageSize = 6; // Số lượng mục trên mỗi trang

            var users = await _userRepository.GetAllAsync();

            var userRoles = new Dictionary<string, List<string>>();
            foreach (var user in users)
            {
                var userRoleNames = await _userRepository.GetUserRolesAsync(user.Id);
                userRoles.Add(user.Id, userRoleNames.ToList());
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                users = await _userRepository.GetByNameAsync(searchString);
            }
            var viewModel = new UserRolesViewModel
            {
                Users = users.ToPagedList(pageNumber, pageSize),
                UserRoles = userRoles
            };
            return View(viewModel);
        }
        public async Task<IActionResult> Display(string id)
        {
            var user = await _userRepository.GetByIdAsync(id);
            return View(user);
        }
        [HttpGet]
        public async Task<IActionResult> UpdateRole(string id)
        {
            // Tìm người dùng với userId cung cấp
            var user = await _userRepository.GetByIdAsync(id);
            if (user == null)
            {
                return NotFound("User not found.");
            }

            // Lấy tất cả các role hiện có từ RoleManager
            var allRoles = _roleManager.Roles.ToList();

            // Lấy role của người dùng
            var userRoles = await _userManager.GetRolesAsync(user);

            // Tạo danh sách SelectListItem từ danh sách role
            var roleItems = allRoles.Select(role => new SelectListItem
            {
                Text = role.Name,
                Value = role.Name,
                Selected = userRoles.Contains(role.Name)
            }).ToList();

            // Chuyển dữ liệu vào view model
            var viewModel = new UserEditViewModel
            {
                UserId = id,
                UserEmail = user.Email,
                Roles = roleItems
            };

            return View(viewModel);
        }

        // Action xử lý việc thay đổi role của người dùng
        [HttpPost]
        public async Task<IActionResult> UpdateRole(UserEditViewModel model)
        {
            // Tìm người dùng với userId cung cấp
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                return NotFound("User not found.");
            }

            // Xóa tất cả các role hiện tại của người dùng
            var currentRoles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, currentRoles);

            // Thêm role mới đã chọn
            await _userManager.AddToRoleAsync(user, model.SelectedRole);

            return RedirectToAction(nameof(Index)); // Chuyển hướng sau khi thực hiện thay đổi
        }
        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            var user = await _userRepository.GetByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

          
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Update(string id, ApplicationUser user)
        {
            if (!ModelState.IsValid)
            {
               
                return View(user);
            }

            var user_ = await _userRepository.GetByIdAsync(id);
            if (user_ == null)
            {
                return NotFound();
            }

            user_.PhoneNumber = user.PhoneNumber;           
            user_.FullName = user.FullName;
            user_.Age = user.Age;

          
            await _userRepository.UpdateAsync(user_);
            return RedirectToAction(nameof(Index));
        }


    }
}

Nhom1_LTWEB_Webbandongho/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Nhom1_LTWEB_Webbandongho.Extensions;
using Nhom1_LTWEB_Webbandongho.Models;
using Nhom1_LTWEB_Webbandongho.Repositories;

namespace Nhom1_LTWEB_Webbandongho.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public ShoppingCartController(IProductRepository productRepository,
            UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _context = context;
            _userManager = userManager;
            _productRepository = productRepository;
        }
       
        public IActionResult OrderCompleted()
        {
            // Lấy thông tin đơn hàng từ database sử dụng orderId và truyền vào view
            
            return View();
        }
        
        public IActionResult Checkout()
        {
            return View(new Order());
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart == null || !cart.Items.Any())
            {
                // Xử lý giỏ hàng trống...
                return RedirectToAction("Index");
            }
            var user = await _userManager.GetUserAsync(User);
            order.UserId = user.Id;
            order.OrderDate = DateTime.UtcNow;
            order.TotalPrice = cart.Items.Sum(i => i.Price * i.Quantity);
            order.OrderDetails = cart.Items.Select(i => new OrderDetail
            {
                ProductId = i.ProductId,
                Quantity = i.Quantity,
                Price = i.Price
            }).ToList();
            _context.Orders.Add(order);
            await _context.SaveChangesAsync();
            HttpContext.Session.Remove("Cart");
            return View("OrderCompleted", order.Id);  // Trang xác nhận hoàn thành đơn hàng

        }
        
        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            // Giả sử bạn có phương thức lấy thông tin sản phẩm từ productId
            var product = await GetProductFromDatabase(productId);
            var cartItem = new CartItem
            {
                ProductId = productId,
                Name = product.Name,
                Price = product.Price,
                Quantity = quantity
            };
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new ShoppingCart();
            cart.AddItem(cartItem);
            HttpContext.Session.SetObjectAsJson("Cart", cart);
            return RedirectToAction("Index", "Home");
        }
        public async Task<Product> GetProductFromDatabase(int productId)
        {
            var product = await _productRepository.GetByIdAsync(productId);
            return product;
        }
        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
                ShoppingCart();
            return View(cart);
        }
        public IActionResult RemoveFromCart(int productId)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart is not null)
            {
                cart.RemoveItem(productId);
                // Lưu lại giỏ hàng vào Session sau khi đã xóa mục
                HttpContext.Session.SetObjectAsJson("Cart", cart);
            }
            return RedirectToAction("Index");
        }
    }
}

Nhom1_LTWEB_Webbandongho/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nhom1_LTWEB_Webbandongho</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Nhom1_LTWEB_Webbandongho.styles.css" asp-append-version="true" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md bg-white navbar-light">
            <div class="container">
                <!-- logo  -->
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: rgb(0, 0, 187);"><b>Nhom1_LTWEB_Webbandongho</b></a>

                <!-- navbar-toggler  -->
                <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse"
                        data-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="collapsibleNavId" >
                    <!-- form tìm kiếm  -->
                    <form class="form-inline ml-auto my-2 my-lg-0 mr-3" method="get" action="@Url.Action("index") " autocomplete="off">
                        @Html.AntiForgeryToken()
                        <div class="input-group autocomplete" style="width: 520px;" autocomplete="off">
                            <input type="text" class="form-control" aria-label="Small"
                                   placeholder="Nhập tên sản phẩm cần tìm kiếm..." name="searchString" id="myInput">
                            <div class="input-group-append">
                                <button type="submit" class="btn" style="background-color: rgb(0, 0, 196); color: white;">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>                          
                        </div>   
                    </form>

                    <!-- ô đăng nhập đăng ký giỏ hàng trên header  -->
                    <ul class="navbar-nav mb-1 ml-auto">
                        <div class="dropdown">
                            <partial name="_LoginPartial" />
                        </div>
                        <form class="d-flex">
                            @Html.AntiForgeryToken()
                            <button class="btn btn-outline-dark" asp-area="" type="submit" asp-controller="ShoppingCart" asp-action="Index">
                                <i class="bi bi-cart-fill"></i>
                                Cart
                            </button>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="nav-bg">
            <nav class="container">
                <ul class="main-menu">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                    <li><a href="#">Sản phẩm</a></li>
                    <li>
                        <a href="#">Danh mục <i class="fa fa-caret-down fa-css"></i></a>
                        <ul class="sub-menu">
                            <li><a href="#">Đồng hồ nữ</a></li>
                            <li><a href="#">Đồng hồ nam</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Thương hiệu <i class="fa fa-caret-down fa-css"></i></a>
                        <ul class="sub-menu">
                            <li><a href="#">Apple</a></li>
                            <li><a href="#">Samsung</a></li>
                            <li><a href="#">Oppo</a></li>
                            <li><a href="#">Garmin</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Tin tức <i class="fa fa-caret-down fa-css"></i></a>
                        <ul class="sub-menu">
                            <li><a href="#">Tin tức 1</a></li>
                            <li><a href="#">Tin tức 2</a></li>
                            <li><a href="#">Tin tức 3</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Liên hệ</a></li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li >
                            <a  asp-area="Admin" asp-controller="Product" asp-action="Index">QuanLySanPham</a>
                        </li>
                        <li >
                            <a asp-area="Admin" asp-controller="User" asp-action="Index">QuanLyUser</a>
                        </li>
                        <li>
                            <a asp-area="Admin" asp-controller="Catelogy" asp-action="Index">QuanLyTheLoai</a>
                        </li>
                    }
                    @if (User.IsInRole("Employee"))
                    {
                        <li class="nav-item">
                            <a  asp-area="Employer" asp-controller="Product" asp-action="Index">QuanLySanPham</a>
                        </li>
                    }
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">      
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container py-4">
            <div class="row">
                <div class="col-md-3 coxl-xs-6">
                    <div class="gioithieu">
                        <h3 class="header text-uppercase font-weight-bold">Về WDONGHO</h3>
                        <a href="#">Giới thiệu về WDONGHO</a>
                        <a href="#">Tuyển dụng</a>
                        <div class="fb-like" data-href=""
                             data-width="300px" data-layout="button" data-action="like" data-size="small"
                             data-share="true"></div>
                    </div>
                </div>
                <div class="col-md-3 col-xs-6">
                    <div class="hotrokh">
                        <h3 class="header text-uppercase font-weight-bold">HỖ TRỢ KHÁCH HÀNG</h3>
                        <a href="#">Hướng dẫn đặt hàng</a>
                        <a href="#">Phương thức thanh toán</a>
                        <a href="#">Phương thức vận chuyển</a>
                        <a href="#">Chính sách đổi trả</a>
                    </div>
                </div>
                <div class="col-md-3 col-xs-6">
                    <div class="lienket">
                        <h3 class="header text-uppercase font-weight-bold">HỢP TÁC VÀ LIÊN KẾT</h3>
                        <a>Trong quá trình xây dựng và phát triển, WDongho đã duy trì được mối quan hệ bền vững với nhiều đối tác chiến lược. Có được sự thành công như ngày hôm nay chính là nhờ vào chất lượng sản phẩm và dịch vụ mà WDongHo đem lại cho khách hàng.</a>
                    </div>
                </div>
                <div class="col-md-3 col-xs-6">
                    <div class="ptthanhtoan">
                        <h3 class="header text-uppercase font-weight-bold">Phương thức thanh toán</h3>
                        <img src="~/images/visa-payment.jpg" alt="visa-payment">
                        <img src="~/images/master-card-payment.jpg" alt="master-card-payment">
                        <img src="~/images/jcb-payment.jpg" alt="jcb-payment">
                        <img src="~/images/payoo-payment.jpg" alt="payoo-payment">
                    </div>
                </div>
            </div>
        </div>
    </footer>
   
    <script>
      
        var autocompleteUrl = '@Url.Action("Autocomplete", "Home")';

        $(document).ready(function () {
            var myInput = document.getElementById("myInput");
            myInput.addEventListener("keyup", function (event) {
                var searchString = this.value;
                $.ajax({
                    url: autocompleteUrl,
                    data: { searchString: searchString },
                    dataType: "json",
                    type: "GET",
                    success: function (data) {
                        var search_sach = data;
                        console.log(data)
                        autocomplete(document.getElementById("myInput"), search_sach);
                    }
                });
            });
        });
    </script>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script> 
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="~/js/AutoSreach.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>